---
title: "Manuscript Style Tips"
author: "Jieying Jiao"
date: \today
output: pdf_document
header-includes:
   - \usepackage{hyperref}
---

# Manuscript style
\begin{enumerate}
\item Always spell check.
\item When revising the paper, answer how the comments are addressed, in blue.
      When the comments are solved, just delete that comments.
\item No space before a paragraph. Use two blank lines to separate paragraphs and
      no space in blank line.
\item Make line width below 80 characters.
\item Do not start a sentence with a symbol or a number.
\item No comma or long words in inline math mode.
\item Put a space before every left parenthesis.
\item Explain each symbol after equations/formulas starting with ``where'' so
      that readers fully understand them. Explanations for one equation/formula
      should be put in one single sentence. Never end a sentence with an
      undefined symbol. No blank line so that no new paragraph is started before
      or after math mode (Don't put formula alone as a paragraph).
\item Put captions for tables on the top while captions for figures on the bottom.
\item Use ``Table'', ``Figure'', ``Equation'' when citing them. Capitalize the
      first letter, and do not use abbreviations.
\item Use past tense to describe the data generation in simulation studies.
\item Figures/tables and other floaters are always positioned with ``tbp''.
      Never use ``h'' in floating table/figure.
\item Label equations, tables and figures which will be referenced and label 
      them use informative names. Don't label those which won't be referenced.
\item Label and cite each each section if needed. Never use the number to 
      represent a section, like ``Section two is about ...''
\item No space in object or identifier (file/project/variable/label) names.
\item Do not include words that have appeared in the title in keywords. 
\item Use ``citep'' when citing paper with parentheses. If the previous definition
      has a specific abbreviation, such as the Akaike Information Criterion,
      use ``citep[AIC;][akaike1973]''.
\item In math mode, use different sized parentheses for better view.
\item Define the distribution instead of distribution name only. For example, 
      for the gamma distribution, don't only define that G is shorthand of Gamma.
\item In math formulas, do not use ``$\times$'' for multiplication unless in a new line.
\item Put enough space in math formulas for better view in source.
\item No inline ``frac''.
\item Use a consistent labeling system, like sec, fig, tab, eq, alg, etc.
\item Do not define unnecessary symbols. Use reasonable and simple symbols. For instance, 
      do not use $a_1$ if you don't have an $a_2$, just $a$ is enough.
\item Use ``$\backslash$dd'' for differentiation operator. Define new command: 
      $\backslash$newcommand\{$\backslash$dd\}\{$\backslash$mathrm\{d\}\}.
      The same command can also be found in the ``physics'' package.
\item Cite the original paper instead of book for appropriate credit.
\item Close a sentence with a period, even in an equation.
\item Never start a sentence with ``And''.
\item Avoid starting a new line with a number. Use tilde in Tex source file to connect 
      text and number.
\item Cite equations using ``eqref'' instead of ``ref''.
\item Never use abbreviations, like ``don't''.
\item Delete extra empty rows.
\item Don't use bullet points in a paper. Rephrase and organize them into a paragraph.
\item No brackets in citing sections/tables/figures.
\item Don't break lines in inline math mode.
\item Use vector form if possible instead of summation.
\item When citing a formula/equation, don't use word ``Formula'' or ``Equation'', 
      just directly cite it using ``eqref''.
\item Use a different font for code, e.g., ``\textbackslash textsf''.
\item Learn how to use ``and'' when listing. Don't use ``$\$a, b\$$'', use 
      ``$\$a\$$ and $\$b\$$'' (no comma in inline math mode).
\item Use uppercase letter for random variables.
\item Any equation needs to be part of a sentence. Punctuation are needed.
\item Break long inline math expressions into multiple pieces.
\item No repeated package using in the preamble.
\item When you list items, the last item has an ``and''.
\item Keywords are alphabetical; no repetition of words in title.
\item Never colon a floater.
\item Put table/figure first and then discuss in tex source.
\item No need to define acronyms that are not used the again.
\item Learn how to use tense in academic writings: \url{https://services.unimelb.edu.au/__data/assets/pdf_file/0009/471294/Using_tenses_in_scientific_writing_Update_051112.pdf}
\item The first sentence of each paragraph shold serve as a title whenever possible.
\item Do not start a sentence with but/so/and in formal writing:
      \url{https://getitwriteonline.com/articles/starting-sentences-and-but/}
\item Do not use who did what way to review the literature, which easily becomes an unordered list. 
      Use your own summary and use citep to back up.
\item Do not abuse the tilde sign to make a very long character unbreakable.
\end{enumerate}


# Figure style
\begin{enumerate}
\item Use pdf or eps for figure file. Do not use png file since it is not vector 
      graphics and will lose resolution when re-size.
\item For line plots with different groups, use different line pattern to
      distinguish them, not only color, so that readers can tell the difference
      when printing them out. Same for different dots on plots.
\item Do not use red and green for different in plots. Some people are 
      red-green blind.
\item Keep figure aspect ratio correct if the figure has realistic meaning.
      Like a basketball half court should be 50/47.
\item Remove extra margin in plot.
\item When change plot size in latex, keep the ratio fixed.
\item For plot files in Tex, name the files informatively.
\item Do not put the figures in an upper level directory. Should be in the 
      same directory or a sub-directory.
\item Do not put sources of table and figure in the same paragraph (with no 
      line breaks).
\end{enumerate}


# Table style
\begin{enumerate}
\item Do not change font size for tables. Change table layout to fit instead
      of re-sizing it. Try to avoid sideways table.
\item Use booktabs effectively. Never use ``hline'' in table. Use ``toprule'',
      ``midrule'', ``bottomrule''.
\item When display estimating results, put variable names in a table, instead of
      their coefficients.
\item Protect negative sign in the table.
\item Right adjust the numbers in tables.
\end{enumerate}

# Manuscript content style
\begin{enumerate}
\item In general, open the abstract with a background of the research problem.
\item One sentence about the findings from the real data analysis in abstract.
\item When introducing the model or method you use, directly start from the data 
      and then introduce the model, method.
\item When discussing results, set up a few bullet points on what you see in the 
      results. Then say them in a nice flow.
\item Show simulation settings in detail and clearly so that readers can
      reproduce your results. Always justify your simulation settings.
\item Put technical details in Appendix.
\item Use precise expression. Try to keep the language simple and clear.
\end{enumerate}

# BibTeX file style
\begin{enumerate}
\item Delete repeated entries.
\item Capitalize first letter of every words in title, except articles, 
      prepositions, or coordinating conjunctions like ``a'', ``in'', ``and''.
\item Always check the BibTeX information downloaded from website. There might 
      be wrong or incomplete information. Google scholar’s BibTeX needs to be 
      quality controlled.
\item Use informative label for each entry: ``Last name + First word in title + year''.
\item For books, use title style.
\item Protect capital letters using ``$\{\}$'', such as in ``Monte Carlo", ``Bayesian",
      and ``Dirichlet".
\item Bib entry keys should have a consistent naming convention in bib title, 
      anything after a colon should be capitalized.
\item Book needs to have publisher and address fields      .
\item For unpublished references, always check if they have been published 
      recently.
\item All references without page numbers or volume number should be checked.
\end{enumerate}

# Using git
\begin{enumerate}
\item Use git and keep it clean (only keep source file, do not keep generated 
      file, eg, .out, .log and generated pdf file).
\end{enumerate}

# File Naming
\begin{enumerate}
\item Name the file using a consistent style. The file name should be 
      informative, no space in it.
\item Usually a repo should have ``manuscript'', ``data'' and ``code'' files.
\end{enumerate}